### PR TITLE
Fixes #2: UI does not update after connection failure

### LINKED ISSUE #2: UI stops polling after request failure
The front-end will stop polling for the scoreboard/slots if a request fails and generates an exception.

This is probably because `fetching` is never set back to false if an exception is thrown.

### PR DESCRIPTION
**Pull request by BrandonDusseau**
Also allows the UI to be viewed by external hosts.

### CODE REVIEW

File: pyfahviewer/static/main.js [hunk 1]
```diff
@@ -40,8 +44,14 @@
   }
 
   async function refreshSlots() {
-    let response = await fetch(`${host}/api/slots`);
-    if (!response.ok) {
+    let response = null;
+    try {
+      response = await fetch("/api/slots");
+    } catch (e) {
+      console.log("Error when fetching slots: " + e);
```
Comment (tjhorner) [inline pyfahviewer/static/main.js:51]: Suggestion: Using `console.error` and passing the error as an argument instead of `console.log`/concatenation will make it stand out in the console more and also retain other info like the stack trace:

image
